stages:
  - dependencies
  - test
  - build
  - publish

install_dependencies:
  image: node:16-alpine
  stage: dependencies
  script:
    - npm install
  only:
    - develop
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

build_image:
  image: node:16-alpine
  stage: build
  script:
    - npm link @angular/cli@12.2.17
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull